### ISSUE TITLE
Store-framework throws Render Server error.

### ISSUE THREAD

**Issue by leomuzicarvalho** [vtex-apps/store-framework-course#12]
**Description**

After cloning linking my own store-framework repo, everything is fine on vscode:

![image](https://user-images.githubusercontent.com/45275689/91232507-9b06fa80-e705-11ea-8537-cd420ed62060.png)

It says the website is live and linked, but when I access it, it opens Render Server error:

![image](https://user-images.githubusercontent.com/45275689/91232545-ae19ca80-e705-11ea-8454-184186d623fb.png)

**Comment by fabianaferreira** [comment]
Solved on [this issue](https://github.com/vtex-apps/store-discussion/issues/401) from Store Discussion.
